=== coronium/isiscb-jsonld-conversion/src/isiscb/schemas/citation.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "IsisCB Citation Schema",
    "description": "JSON Schema for IsisCB Citation JSON-LD documents",
    "type": "object",
    "required": ["@context", "@id", "@type"],
    "properties": {
      "@context": {
        "description": "JSON-LD context definition",
        "oneOf": [
          {"type": "string", "format": "uri"},
          {"type": "object"},
          {
            "type": "array",
            "items": {
              "oneOf": [
                {"type": "string", "format": "uri"},
                {"type": "object"}
              ]
            }
          }
        ]
      },
      "@id": {
        "type": "string",
        "format": "uri",
        "description": "Unique identifier for the citation",
        "pattern": "^https://data\\.isiscb\\.org/citation/CBB\\d+"
      },
      "@type": {
        "description": "Type of the citation",
        "oneOf": [
          {"type": "string"},
          {"type": "array", "items": {"type": "string"}}
        ]
      },
      "dc:title": {
        "type": "string",
        "description": "Title of the citation"
      },
      "isiscb:mainTitle": {
        "type": "string",
        "description": "Main title without subtitle"
      },
      "isiscb:subtitle": {
        "type": "string",
        "description": "Subtitle of the citation"
      },
      "dc:creator": {
        "description": "Creator(s) of the work",
        "oneOf": [
          {"type": "string"},
          {"type": "object"},
          {"type": "array", "items": {"oneOf": [{"type": "string"}, {"type": "object"}]}}
        ]
      },
      "dc:contributor": {
        "description": "Contributor(s) to the work",
        "oneOf": [
          {"type": "string"},
          {"type": "object"},
          {"type": "array", "items": {"oneOf": [{"type": "string"}, {"type": "object"}]}}
        ]
      },
      "dc:date": {
        "type": "string",
        "description": "Publication date"
      },
      "dc:publisher": {
        "description": "Publisher of the work",
        "oneOf": [
          {"type": "string"},
          {"type": "object"}
        ]
      },
      "dc:language": {
        "description": "Language of the work",
        "oneOf": [
          {"type": "string"},
          {"type": "array", "items": {"type": "string"}}
        ]
      },
      "dc:subject": {
        "description": "Subject(s) of the work",
        "oneOf": [
          {"type": "string"},
          {"type": "object"},
          {"type": "array", "items": {"oneOf": [{"type": "string"}, {"type": "object"}]}}
        ]
      },
      "isiscb:recordID": {
        "type": "string",
        "description": "IsisCB identifier for the citation",
        "pattern": "^CBB\\d+"
      },
      "isiscb:recordType": {
        "type": "string",
        "description": "Type of record in the IsisCB system",
        "enum": [
          "Book", 
          "Article", 
          "Chapter", 
          "Review", 
          "Essay", 
          "Thesis", 
          "Conference Proceeding",
          "Conference Paper",
          "Website",
          "Report"
        ]
      },
      "isiscb:recordStatus": {
        "type": "string",
        "description": "Status of the record in the IsisCB system"
      },
      "isiscb:recordNatureOriginal": {
        "type": "string",
        "description": "Original record nature value"
      },
      "bibo:pages": {
        "type": "string",
        "description": "Page range of the citation"
      },
      "prism:volume": {
        "oneOf": [
          {"type": "string"},
          {"type": "number"}
        ],
        "description": "Volume number for journal articles"
      },
      "prism:number": {
        "oneOf": [
          {"type": "string"},
          {"type": "number"}
        ],
        "description": "Issue number for journal articles"
      }
    },
    "additionalProperties": true
  }

=== coronium/isiscb-jsonld-conversion/data/processed/test_citation_20250308_145735.json
[
  {
    "@context": {
      "dc": "http://purl.org/dc/elements/1.1/",
      "dcterms": "http://purl.org/dc/terms/",
      "schema": "http://schema.org/",
      "bibo": "http://purl.org/ontology/bibo/",
      "foaf": "http://xmlns.com/foaf/0.1/",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "prism": "http://prismstandard.org/namespaces/basic/2.0/",
      "isiscb": "https://ontology.isiscb.org/vocabulary/",
      "schema:name": {
        "@id": "dc:title"
      },
      "isiscb:title": {
        "@id": "dc:title"
      },
      "schema:author": {
        "@id": "dc:creator"
      },
      "isiscb:author": {
        "@id": "dc:creator"
      },
      "schema:datePublished": {
        "@id": "dc:date"
      },
      "isiscb:publicationDate": {
        "@id": "dc:date"
      },
      "schema:publisher": {
        "@id": "dc:publisher"
      },
      "schema:about": {
        "@id": "dc:subject"
      },
      "schema:inLanguage": {
        "@id": "dc:language"
      },
      "schema:identifier": {
        "@id": "dc:identifier"
      }
    },
    "@id": "https://data.isiscb.org/citation/CBB262293571",
    "isiscb:recordID": "CBB262293571",
    "@type": [
      "bibo:Article",
      "schema:ScholarlyArticle",
      "isiscb:Article"
    ],
    "isiscb:recordStatus": "isiscb:statusActive",
    "isiscb:recordNatureOriginal": "Active (RecordStatusExplanation Inactive by default)",
    "dc:title": "Love Is a Problem of Knowledge"
  },
  {
    "@context": {
      "dc": "http://purl.org/dc/elements/1.1/",
      "dcterms": "http://purl.org/dc/terms/",
      "schema": "http://schema.org/",
      "bibo": "http://purl.org/ontology/bibo/",
      "foaf": "http://xmlns.com/foaf/0.1/",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "prism": "http://prismstandard.org/namespaces/basic/2.0/",
      "isiscb": "https://ontology.isiscb.org/vocabulary/",
      "schema:name": {
        "@id": "dc:title"
      },
      "isiscb:title": {
        "@id": "dc:title"
      },
      "schema:author": {
        "@id": "dc:creator"
      },
      "isiscb:author": {
        "@id": "dc:creator"
      },
      "schema:datePublished": {
        "@id": "dc:date"
      },
      "isiscb:publicationDate": {
        "@id": "dc:date"
      },
      "schema:publisher": {
        "@id": "dc:publisher"
      },
      "schema:about": {
        "@id": "dc:subject"
      },
      "schema:inLanguage": {
        "@id": "dc:language"
      },
      "schema:identifier": {
        "@id": "dc:identifier"
      }
    },
    "@id": "https://data.isiscb.org/citation/CBB550080731",
    "isiscb:recordID": "CBB550080731",
    "@type": [
      "bibo:Article",
      "schema:ScholarlyArticle",
      "isiscb:Article"
    ],
    "isiscb:recordStatus": "isiscb:statusActive",
    "isiscb:recordNatureOriginal": "Active (RecordStatusExplanation Inactive by default)",
    "dc:title": "The Triumph of Theriac: Print, Apothecary Publications, and the Commodification of Ancient Antidotes (1497–1800)"
  },
  {
    "@context": {
      "dc": "http://purl.org/dc/elements/1.1/",
      "dcterms": "http://purl.org/dc/terms/",
      "schema": "http://schema.org/",
      "bibo": "http://purl.org/ontology/bibo/",
      "foaf": "http://xmlns.com/foaf/0.1/",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "prism": "http://prismstandard.org/namespaces/basic/2.0/",
      "isiscb": "https://ontology.isiscb.org/vocabulary/",
      "schema:name": {
        "@id": "dc:title"
      },
      "isiscb:title": {
        "@id": "dc:title"
      },
      "schema:author": {
        "@id": "dc:creator"
      },
      "isiscb:author": {
        "@id": "dc:creator"
      },
      "schema:datePublished": {
        "@id": "dc:date"
      },
      "isiscb:publicationDate": {
        "@id": "dc:date"
      },
      "schema:publisher": {
        "@id": "dc:publisher"
      },
      "schema:about": {
        "@id": "dc:subject"
      },
      "schema:inLanguage": {
        "@id": "dc:language"
      },
      "schema:identifier": {
        "@id": "dc:identifier"
      }
    },
    "@id": "https://data.isiscb.org/citation/CBB317984823",
    "isiscb:recordID": "CBB317984823",
    "@type": [
      "bibo:Article",
      "schema:ScholarlyArticle",
      "isiscb:Article"
    ],
    "isiscb:recordStatus": "isiscb:statusActive",
    "isiscb:recordNatureOriginal": "Active (RecordStatusExplanation Inactive by default)",
    "dc:title": "Galileo’s Two New Sciences as a Model of Reading Practice"
  },
  {
    "@context": {
      "dc": "http://purl.org/dc/elements/1.1/",
      "dcterms": "http://purl.org/dc/terms/",
      "schema": "http://schema.org/",
      "bibo": "http://purl.org/ontology/bibo/",
      "foaf": "http://xmlns.com/foaf/0.1/",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "prism": "http://prismstandard.org/namespaces/basic/2.0/",
      "isiscb": "https://ontology.isiscb.org/vocabulary/",
      "schema:name": {
        "@id": "dc:title"
      },
      "isiscb:title": {
        "@id": "dc:title"
      },
      "schema:author": {
        "@id": "dc:creator"
      },
      "isiscb:author": {
        "@id": "dc:creator"
      },
      "schema:datePublished": {
        "@id": "dc:date"
      },
      "isiscb:publicationDate": {
        "@id": "dc:date"
      },
      "schema:publisher": {
        "@id": "dc:publisher"
      },
      "schema:about": {
        "@id": "dc:subject"
      },
      "schema:inLanguage": {
        "@id": "dc:language"
      },
      "schema:identifier": {
        "@id": "dc:identifier"
      }
    },
    "@id": "https://data.isiscb.org/citation/CBB123318800",
    "isiscb:recordID": "CBB123318800",
    "@type": [
      "bibo:Article",
      "schema:ScholarlyArticle",
      "isiscb:Article"
    ],
    "isiscb:recordStatus": "isiscb:statusActive",
    "isiscb:recordNatureOriginal": "Active (RecordStatusExplanation )",
    "dc:title": "Frontier of Professionals:The Vision of American Advisors That Supported Hokkaido Development in the Early Meiji Period"
  },
  {
    "@context": {
      "dc": "http://purl.org/dc/elements/1.1/",
      "dcterms": "http://purl.org/dc/terms/",
      "schema": "http://schema.org/",
      "bibo": "http://purl.org/ontology/bibo/",
      "foaf": "http://xmlns.com/foaf/0.1/",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "prism": "http://prismstandard.org/namespaces/basic/2.0/",
      "isiscb": "https://ontology.isiscb.org/vocabulary/",
      "schema:name": {
        "@id": "dc:title"
      },
      "isiscb:title": {
        "@id": "dc:title"
      },
      "schema:author": {
        "@id": "dc:creator"
      },
      "isiscb:author": {
        "@id": "dc:creator"
      },
      "schema:datePublished": {
        "@id": "dc:date"
      },
      "isiscb:publicationDate": {
        "@id": "dc:date"
      },
      "schema:publisher": {
        "@id": "dc:publisher"
      },
      "schema:about": {
        "@id": "dc:subject"
      },
      "schema:inLanguage": {
        "@id": "dc:language"
      },
      "schema:identifier": {
        "@id": "dc:identifier"
      }
    },
    "@id": "https://data.isiscb.org/citation/CBB234311668",
    "isiscb:recordID": "CBB234311668",
    "@type": [
      "bibo:Article",
      "schema:ScholarlyArticle",
      "isiscb:Article"
    ],
    "isiscb:recordStatus": "isiscb:statusActive",
    "isiscb:recordNatureOriginal": "Active (RecordStatusExplanation Inactive by default)",
    "dc:title": "Defects in Doubt Manufacturing: The Trajectory of a Pro-industrial Argument in the Struggle for the Definition of Carcinogenic Substances"
  },
  {
    "@context": {
      "dc": "http://purl.org/dc/elements/1.1/",
      "dcterms": "http://purl.org/dc/terms/",
      "schema": "http://schema.org/",
      "bibo": "http://purl.org/ontology/bibo/",
      "foaf": "http://xmlns.com/foaf/0.1/",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "prism": "http://prismstandard.org/namespaces/basic/2.0/",
      "isiscb": "https://ontology.isiscb.org/vocabulary/",
      "schema:name": {
        "@id": "dc:title"
      },
      "isiscb:title": {
        "@id": "dc:title"
      },
      "schema:author": {
        "@id": "dc:creator"
      },
      "isiscb:author": {
        "@id": "dc:creator"
      },
      "schema:datePublished": {
        "@id": "dc:date"
      },
      "isiscb:publicationDate": {
        "@id": "dc:date"
      },
      "schema:publisher": {
        "@id": "dc:publisher"
      },
      "schema:about": {
        "@id": "dc:subject"
      },
      "schema:inLanguage": {
        "@id": "dc:language"
      },
      "schema:identifier": {
        "@id": "dc:identifier"
      }
    },
    "@id": "https://data.isiscb.org/citation/CBB704973598",
    "isiscb:recordID": "CBB704973598",
    "@type": [
      "bibo:Article",
      "schema:ScholarlyArticle",
      "isiscb:Article"
    ],
    "isiscb:recordStatus": "isiscb:statusActive",
    "isiscb:recordNatureOriginal": "Active (RecordStatusExplanation Inactive by default)",
    "dc:title": "Economizing Socialist Aid: China's Failed Surgical Plant in Algeria, 1973–80"
  },
  {
    "@context": {
      "dc": "http://purl.org/dc/elements/1.1/",
      "dcterms": "http://purl.org/dc/terms/",
      "schema": "http://schema.org/",
      "bibo": "http://purl.org/ontology/bibo/",
      "foaf": "http://xmlns.com/foaf/0.1/",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "prism": "http://prismstandard.org/namespaces/basic/2.0/",
      "isiscb": "https://ontology.isiscb.org/vocabulary/",
      "schema:name": {
        "@id": "dc:title"
      },
      "isiscb:title": {
        "@id": "dc:title"
      },
      "schema:author": {
        "@id": "dc:creator"
      },
      "isiscb:author": {
        "@id": "dc:creator"
      },
      "schema:datePublished": {
        "@id": "dc:date"
      },
      "isiscb:publicationDate": {
        "@id": "dc:date"
      },
      "schema:publisher": {
        "@id": "dc:publisher"
      },
